### ISSUE TITLE
event is undefined in $onBlur of QUISelect

### ISSUE THREAD

**Issue by QUIQQER** [QUIQQER/qui#1]
```
File: https://juicer.namefruits.de/packages/bin/qui/qui/controls/buttons/Select.js?update=1518425466
Line Number: 902
Error: TypeError: event is undefined
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0
```

Seems to be happening on Firefox on Mac OS X.

original issue: https://dev.quiqqer.com/quiqqer/qui/issues/36
original finder: @peat85

**Comment by QUIQQER** [comment]
Same problem with undefined `event` Mac OS X (different Browser)

```
File: https://juicer.namefruits.de/packages/bin/qui/qui/controls/buttons/Select.js?update=1518425466
Line Number: 902
Error: Uncaught TypeError: Cannot read property 'stop' of undefined
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36
```

**Comment by dehenne** [comment]
For better understandig from another project:

![image](https://user-images.githubusercontent.com/751811/36213630-7e76523e-11a7-11e8-8e40-4d136f540405.png)

**Comment by dehenne** [comment]
Fix: https://github.com/QUIQQER/qui/commit/1d515a602f214db6f9122fccb17b216db2b62fad
